version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
    npm:
      image: node:current-alpine
      environment:
        - NODE_OPTIONS=--openssl-legacy-provider
      volumes:
        - .:/var/www/html
      entrypoint: ['npm']